acme_store_homepage:
    pattern:  /create
    defaults: { _controller: AcmeStoreBundle:Default:index }
acme_store_show:
    pattern:  /show
    defaults: { _controller: AcmeStoreBundle:Default:show }
